import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Green Seoul Bot',
  description: 'Generated by G.cycle',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html>
      <body>{children}</body>
    </html>
  )
}
